require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CdPagesController do

  def mock_cd_page(stubs={})
    @mock_cd_page ||= mock_model(CdPage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cd_pages as @cd_pages" do
      CdPage.stub(:all) { [mock_cd_page] }
      get :index
      assigns(:cd_pages).should eq([mock_cd_page])
    end
  end

  describe "GET show" do
    it "assigns the requested cd_page as @cd_page" do
      CdPage.stub(:find).with("37") { mock_cd_page }
      get :show, :id => "37"
      assigns(:cd_page).should be(mock_cd_page)
    end
  end

  describe "GET new" do
    it "assigns a new cd_page as @cd_page" do
      CdPage.stub(:new) { mock_cd_page }
      get :new
      assigns(:cd_page).should be(mock_cd_page)
    end
  end

  describe "GET edit" do
    it "assigns the requested cd_page as @cd_page" do
      CdPage.stub(:find).with("37") { mock_cd_page }
      get :edit, :id => "37"
      assigns(:cd_page).should be(mock_cd_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cd_page as @cd_page" do
        CdPage.stub(:new).with({'these' => 'params'}) { mock_cd_page(:save => true) }
        post :create, :cd_page => {'these' => 'params'}
        assigns(:cd_page).should be(mock_cd_page)
      end

      it "redirects to the created cd_page" do
        CdPage.stub(:new) { mock_cd_page(:save => true) }
        post :create, :cd_page => {}
        response.should redirect_to(cd_page_url(mock_cd_page))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cd_page as @cd_page" do
        CdPage.stub(:new).with({'these' => 'params'}) { mock_cd_page(:save => false) }
        post :create, :cd_page => {'these' => 'params'}
        assigns(:cd_page).should be(mock_cd_page)
      end

      it "re-renders the 'new' template" do
        CdPage.stub(:new) { mock_cd_page(:save => false) }
        post :create, :cd_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cd_page" do
        CdPage.stub(:find).with("37") { mock_cd_page }
        mock_cd_page.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cd_page => {'these' => 'params'}
      end

      it "assigns the requested cd_page as @cd_page" do
        CdPage.stub(:find) { mock_cd_page(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cd_page).should be(mock_cd_page)
      end

      it "redirects to the cd_page" do
        CdPage.stub(:find) { mock_cd_page(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cd_page_url(mock_cd_page))
      end
    end

    describe "with invalid params" do
      it "assigns the cd_page as @cd_page" do
        CdPage.stub(:find) { mock_cd_page(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cd_page).should be(mock_cd_page)
      end

      it "re-renders the 'edit' template" do
        CdPage.stub(:find) { mock_cd_page(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cd_page" do
      CdPage.stub(:find).with("37") { mock_cd_page }
      mock_cd_page.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cd_pages list" do
      CdPage.stub(:find) { mock_cd_page }
      delete :destroy, :id => "1"
      response.should redirect_to(cd_pages_url)
    end
  end

end
