require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TricksController do

  def mock_trick(stubs={})
    @mock_trick ||= mock_model(Trick, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tricks as @tricks" do
      Trick.stub(:all) { [mock_trick] }
      get :index
      assigns(:tricks).should eq([mock_trick])
    end
  end

  describe "GET show" do
    it "assigns the requested trick as @trick" do
      Trick.stub(:find).with("37") { mock_trick }
      get :show, :id => "37"
      assigns(:trick).should be(mock_trick)
    end
  end

  describe "GET new" do
    it "assigns a new trick as @trick" do
      Trick.stub(:new) { mock_trick }
      get :new
      assigns(:trick).should be(mock_trick)
    end
  end

  describe "GET edit" do
    it "assigns the requested trick as @trick" do
      Trick.stub(:find).with("37") { mock_trick }
      get :edit, :id => "37"
      assigns(:trick).should be(mock_trick)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created trick as @trick" do
        Trick.stub(:new).with({'these' => 'params'}) { mock_trick(:save => true) }
        post :create, :trick => {'these' => 'params'}
        assigns(:trick).should be(mock_trick)
      end

      it "redirects to the created trick" do
        Trick.stub(:new) { mock_trick(:save => true) }
        post :create, :trick => {}
        response.should redirect_to(trick_url(mock_trick))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trick as @trick" do
        Trick.stub(:new).with({'these' => 'params'}) { mock_trick(:save => false) }
        post :create, :trick => {'these' => 'params'}
        assigns(:trick).should be(mock_trick)
      end

      it "re-renders the 'new' template" do
        Trick.stub(:new) { mock_trick(:save => false) }
        post :create, :trick => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trick" do
        Trick.stub(:find).with("37") { mock_trick }
        mock_trick.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :trick => {'these' => 'params'}
      end

      it "assigns the requested trick as @trick" do
        Trick.stub(:find) { mock_trick(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:trick).should be(mock_trick)
      end

      it "redirects to the trick" do
        Trick.stub(:find) { mock_trick(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(trick_url(mock_trick))
      end
    end

    describe "with invalid params" do
      it "assigns the trick as @trick" do
        Trick.stub(:find) { mock_trick(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:trick).should be(mock_trick)
      end

      it "re-renders the 'edit' template" do
        Trick.stub(:find) { mock_trick(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trick" do
      Trick.stub(:find).with("37") { mock_trick }
      mock_trick.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tricks list" do
      Trick.stub(:find) { mock_trick }
      delete :destroy, :id => "1"
      response.should redirect_to(tricks_url)
    end
  end

end
