---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: pushwood.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-b892f4c0
  image_type: m1.small
  image_id: ami-82fa58eb
  security_groups:
  - pushwood_production_default
  - pushwood_production_web
  - pushwood_production_web01
  - pushwood_production_haproxy
  - pushwood_production_app
  - pushwood_production_passenger_nginx
  - pushwood_production_redis
  - pushwood_production_db
  - pushwood_production_mysql
  - pushwood_production_mysql_master
  - pushwood_production_collectd
  - pushwood_production_monit
  external_host: ec2-23-21-158-34.compute-1.amazonaws.com
  external_ip: 23.21.158.34
  internal_host: domU-12-31-39-0B-18-52.compute-1.internal
  internal_ip: 10.214.31.160
  zone: us-east-1c
  platform: linux
  root_device_type: ebs
  static_ip: 23.21.158.34
- volumes: {}
  static_ips:
    web01: 23.21.158.34
